version: '2'

services:
  firefox:
    image: selenium/standalone-firefox
    shm_size: '2gb'
    privileged: true
    volumes:
      - /dev/shm:/dev/shm
    ports:
      - "4444:4444"
  app:
    container_name: springboot
    image: springboot
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - firefox
      - postgresql
    environment:
      - FF_EMAIL_NAME=${FF_EMAIL_NAME}
      - FF_EMAIL_PASS=${FF_EMAIL_PASS}
      - FF_EMAIL_RECIPIENTS=${FF_EMAIL_RECIPIENTS}
      - SPRING_DATASOURCE_URL=${FF_DB_URL}
      - SPRING_DATASOURCE_USERNAME=${FF_DB_LOGIN}
      - SPRING_DATASOURCE_PASSWORD=${FF_DB_PASS}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      - OLX_API=${OLX_API}
      - MORIZON_API=${MORIZON_API}
      - OTODOM_API=${OTODOM_API}
      - HIBERNATE_SHOW_SQL=${HIBERNATE_SHOW_SQL}
      - MAIL_HOST=${MAIL_HOST}
      - MAIL_PORT=${MAIL_PORT}
  postgresql:
    container_name: postgresql
    image: 'postgres:15.2-alpine'
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${FF_DB_LOGIN}
      - POSTGRES_PASSWORD=${FF_DB_PASS}
      - POSTGRES_DB=${FF_DB}